### ISSUE TITLE
Google Play: Retrieving Install Referrer String in Adjust SDK

### ISSUE THREAD

**Issue by rewb0rn** [adjust/adobe_air_sdk#50]
Hello,

is there a way to retrieve the Android Install Referrer URL from the Adjust SDK? We have previously used Google Analytics to retrieve the Install Referrer, but since this has been deprecated in favor of Firebase, which does not offer an Install Referrer, I would like to know if this can be accessed from Adjust.

Example URL the user opens when installing the app:
```
https://play.google.com/store/apps/details?id=air.XXX&referrer=utm_source%3Dtest_source%26utmMedium%3DtestMedium%26utm_campaign%3DtestCampaign
```

Referrer URL we would receive through Google Analytics and would like to access from Adjust:
```
utm_source=test_source&utmMedium=testMedium&utm_campaign=testCampaign
```

Thanks in advance

**Comment by uerceg** [comment]
Hi @rewb0rn,

For our Adobe AIR SDK users - nope. We are collecting this information on native Android level and pass it to our backend of course, since we need it for attribution purpose, but we do not have any getter for this.

Cheers

**Comment by rewb0rn** [comment]
Any chance this could be added? I imagine it to be a fairly simply change?

Thanks for the quick response!

**Comment by uerceg** [comment]
I will bring this topic up to our product team which is in charge of making these kinds of decisions and let you know. In theory it shouldn't be that much of an issue.

`setReferrer()` method is kinda dummy since it should not be used by outer world, rather it's being used from `AdjustBroadcastReceiver.java` to ping our SDK with referrer info obtained from old style INSTALL_REFERRER intent broadcasting way.

We're now in the middle of work on next major Android SDK update, so if we add this to our SDK, will probably be added in that version (unfortunately no clear ETA).

**Comment by uerceg** [comment]
Hi @rewb0rn 

Forgot to update you on this one. We will be adding this method to our SDK, but (unfortunately) in our next major SDK release. Q1/Q2 2020 should be rough ETA on when we're gonna start unrolling these updates on native SDKs and Adobe AIR will follow up soon-ish afterwards.

Thanks for the idea!

Cheers.

**Comment by rewb0rn** [comment]
Hi, any news on this? Thanks

**Comment by ugi** [comment]
Hey. Unfortunately not yet. We don't have certain ETA for next major update since this virus situation kinda shuffled lots of things around. We'll check if maybe we can add getter for this to v4.
