### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by spielepalast** [adjust/adobe_air_sdk#64]
Is there any plan for adding support for Windows in a foreseeable future? More platform support for Air projects would be amazing overall.

**Comment by uerceg** [comment]
Hey @spielepalast,

Sorry for amazingly belated reply to your question. At this moment, there are no such plans on our end. In case you are still around those projects and willing to reply here, I'm curious how would that work under the hood. What kind of Windows apps are you targeting from your Adobe AIR app? UWP? Windows App SDK? Something else? Are you able to reuse your Adobe AIR app code and run it on all 3 platforms (iOS / Android / Windows)?

Sorry one more time for the delay. I will close this issue due to super late reply on our end, but in case you have any questions / comments, feel free to comment / reply.

**Comment by spielepalast** [comment]
Yes we are targeting ios, android and uwp from one app code base. So we would be interested in uwp.
